=== neaket/Dragonfly/Dragonfly.Game/Dragonfly.Game/Models/WorldSchema1.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="LevelSchema"
    targetNamespace="http://eaket.com/games/dragonfly/WorldSchema1"
    elementFormDefault="qualified"
    xmlns="http://eaket.com/games/dragonfly/WorldSchema1"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!-- common -->
  <xs:complexType name="Vector2">
    <xs:attribute name="X" type="xs:float" />
    <xs:attribute name="Y" type="xs:float" />
  </xs:complexType>

  <xs:simpleType name="BodyType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Static" />
      <xs:enumeration value="Kinematic" />
      <xs:enumeration value="Dynamic" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="Vertices">
    <xs:list itemType="Vertex" >
     
    </xs:list>
  </xs:simpleType>

  <xs:simpleType name="Vertex">
    <xs:restriction base="xs:string">
      <xs:pattern value="[-+]?[0-9]*\.?[0-9]*,[-+]?[0-9]*\.?[0-9]*" />
      <xs:whiteSpace value="collapse"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="PositiveNonZero">
    <xs:restriction base="xs:float" >
      <xs:minExclusive value="0" />
    </xs:restriction>
  </xs:simpleType>
  
  <!-- World Info-->
  <xs:complexType name="WorldInfo">
    <xs:attribute name="Name" type="xs:string" />
    <xs:attribute name="Description" type="xs:string" />
    <xs:attribute name="Language" type="xs:language" />
  </xs:complexType>
  
  <!-- Physics Engine-->
  <xs:complexType name="PhysicsSettings">
    <xs:sequence>
      <xs:element name="Gravity" type="Vector2" />
    </xs:sequence>
  </xs:complexType>
 
  <!-- Valid World Elements-->
  <xs:complexType name="WorldElements">
    <xs:choice maxOccurs="unbounded">
      <xs:element name="BoxElement" type="BoxElement" />
      <xs:element name="CircleElement" type="CircleElement" />
      <xs:element name="ElypsisElement" type="ElypsisElement" />
      <xs:element name="PolygonElement" type="PolygonElement" />
    </xs:choice>
  </xs:complexType>
  
  
  <!-- World Element-->
    <xs:complexType name="WorldElement">
      <xs:sequence>
        <xs:element name="Position" type="Vector2" />
        <xs:element name="Body" type="Body" />
      </xs:sequence>
      <xs:attribute name="Material" type="xs:string" use="optional" />
      <xs:attribute name="Color" type="xs:string" use="optional" />
    </xs:complexType>

  <xs:complexType name="BoxElement">
    <xs:complexContent>
      <xs:extension base="WorldElement">
        <xs:sequence>
          <xs:element name="Size" type="Vector2" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="CircleElement">
    <xs:complexContent>
      <xs:extension base="WorldElement">
        <xs:sequence>
          <xs:element name="Radius" type="xs:float" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="ElypsisElement">
    <xs:complexContent>
      <xs:extension base="WorldElement">
        <xs:sequence>
          <xs:element name="Radius" type="Vector2" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="PolygonElement">
    <xs:complexContent>
      <xs:extension base="WorldElement">
        <xs:sequence>
          <xs:element name="Vertices" type="Vertices" />
        </xs:sequence>        
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="EdgeElement">
    <xs:complexContent>
      <xs:extension base="WorldElement">
        <xs:sequence>
          <xs:element name="start" type="Vector2" />
          <xs:element name="end" type="Vector2" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
   <!-- Body -->
  <xs:complexType name="Body">

    <xs:attribute name="BodyType" type="BodyType" />
    <xs:attribute name="Mass" type="PositiveNonZero" />
    
  </xs:complexType>
  
  <!-- Fixture -->
   
  <!-- Root Element-->
  <xs:element name="World">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="WorldInfo" type="WorldInfo" minOccurs="1"/>
        <xs:element name="PhysicsSettings" type="PhysicsSettings" minOccurs="1" maxOccurs="1" />
        <xs:element name="WorldElements" type="WorldElements" maxOccurs="1" /> 
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== neaket/Dragonfly/Dragonfly.GameContent/Levels/TestLevel1.xml
<?xml version="1.0" encoding="utf-8" ?>
<World
  xmlns="http://eaket.com/games/dragonfly/WorldSchema1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://eaket.com/games/dragonfly/WorldSchema1 WorldSchema1.xsd">
  <WorldInfo 
    Name="Test Level 1"
    Description="This is the first level to be loaded"
    Language="en"/>
  <PhysicsSettings>
    <Gravity X="0" Y="0"/>
  </PhysicsSettings>
  <WorldElements>
    <RectangleElement Color="#ff0000">
      <Position X="20" Y="20"/>
      <Body BodyType="Dynamic" Mass="1"/>
      <Size X="10" Y="10"/>
    </RectangleElement>
    <RectangleElement Color="#00ff00">
      <Position X="100" Y="200"/>
      <Body BodyType="Static" Mass="1"/>
      <Size X="200" Y="5"/>
    </RectangleElement>
  </WorldElements>
</World>
